"""auto migration

Revision ID: 08e1aec42323
Revises: 45c8e8a481cf
Create Date: 2025-02-14 19:52:43.256915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e1aec42323'
down_revision = '45c8e8a481cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###