"""auto migration

Revision ID: 098088eff5ce
Revises: c7e840fd241a
Create Date: 2025-02-14 19:38:40.406548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098088eff5ce'
down_revision = 'c7e840fd241a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###