"""auto migration

Revision ID: 0cc2504f4bb5
Revises: 9bad828da977
Create Date: 2025-02-15 10:55:58.749872

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '0cc2504f4bb5'
down_revision = '9bad828da977'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###