"""auto migration

Revision ID: 208348b86f42
Revises: 73d5d2774f4e
Create Date: 2025-02-14 20:06:56.671827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208348b86f42'
down_revision = '73d5d2774f4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###