"""auto migration

Revision ID: 338b4ada8a9f
Revises: 098088eff5ce
Create Date: 2025-02-14 19:42:10.004611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338b4ada8a9f'
down_revision = '098088eff5ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###