"""auto migration

Revision ID: 361bf593b5e5
Revises: fc852df9b6b0
Create Date: 2025-02-14 18:53:24.681061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361bf593b5e5'
down_revision = 'fc852df9b6b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('text', sa.String(), nullable=True))
    op.add_column('node', sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=False))
    op.create_index(op.f('ix_node_text'), 'node', ['text'], unique=False)
    op.drop_column('node', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_node_text'), table_name='node')
    op.drop_column('node', 'embedding')
    op.drop_column('node', 'text')
    # ### end Alembic commands ###