"""auto migration

Revision ID: 39c5b6ed8db9
Revises: 712e4b4469c9
Create Date: 2025-02-02 15:31:27.259614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c5b6ed8db9'
down_revision = '712e4b4469c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###