"""auto migration

Revision ID: 3cd12dffafad
Revises: df1599c83ea3
Create Date: 2025-02-02 10:52:22.082731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd12dffafad'
down_revision = 'df1599c83ea3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###