"""auto migration

Revision ID: 45c8e8a481cf
Revises: fdb30af36a7f
Create Date: 2025-02-14 19:49:24.719274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c8e8a481cf'
down_revision = 'fdb30af36a7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###