"""auto migration

Revision ID: 53427c5d7864
Revises: 82e970a4f759
Create Date: 2025-02-15 09:53:03.264260

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '53427c5d7864'
down_revision = '82e970a4f759'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('node',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=3072), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_id'), 'node', ['id'], unique=False)
    op.create_index(op.f('ix_node_text'), 'node', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_text'), table_name='node')
    op.drop_index(op.f('ix_node_id'), table_name='node')
    op.drop_table('node')
    # ### end Alembic commands ###