"""auto migration

Revision ID: 58bff891a787
Revises: 63c5d24ee74f
Create Date: 2025-02-14 19:25:14.248647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58bff891a787'
down_revision = '63c5d24ee74f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###