"""auto migration

Revision ID: 63c5d24ee74f
Revises: badc0a1ed09e
Create Date: 2025-02-14 19:07:02.027846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c5d24ee74f'
down_revision = 'badc0a1ed09e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###