"""auto migration

Revision ID: 6bbe9c141ba1
Revises: d023e296adc3
Create Date: 2025-02-02 10:06:36.476948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbe9c141ba1'
down_revision = 'd023e296adc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###