"""auto migration

Revision ID: 6eb91657c9fc
Revises: 6bbe9c141ba1
Create Date: 2025-02-02 10:44:42.747477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb91657c9fc'
down_revision = '6bbe9c141ba1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###