"""auto migration

Revision ID: 712e4b4469c9
Revises: d342e4bd242b
Create Date: 2025-02-02 15:25:20.472596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712e4b4469c9'
down_revision = 'd342e4bd242b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###