"""auto migration

Revision ID: 73d5d2774f4e
Revises: b40d9e870277
Create Date: 2025-02-14 20:04:56.024783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d5d2774f4e'
down_revision = 'b40d9e870277'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###