"""auto migration

Revision ID: 998c1658516b
Revises: c3b22ace8d37
Create Date: 2025-02-14 20:27:08.931215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998c1658516b'
down_revision = 'c3b22ace8d37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###