"""auto migration

Revision ID: badc0a1ed09e
Revises: 361bf593b5e5
Create Date: 2025-02-14 19:05:19.447566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'badc0a1ed09e'
down_revision = '361bf593b5e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_id', table_name='session')
    op.drop_table('session')
    op.drop_index('ix_node_id', table_name='node')
    op.drop_index('ix_node_text', table_name='node')
    op.drop_table('node')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='node_pkey')
    )
    op.create_index('ix_node_text', 'node', ['text'], unique=False)
    op.create_index('ix_node_id', 'node', ['id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='session_pkey')
    )
    op.create_index('ix_session_id', 'session', ['id'], unique=False)
    # ### end Alembic commands ###