"""auto migration

Revision ID: c3b22ace8d37
Revises: 208348b86f42
Create Date: 2025-02-14 20:20:39.249922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b22ace8d37'
down_revision = '208348b86f42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###