"""auto migration

Revision ID: d342e4bd242b
Revises: 3085708c0946
Create Date: 2025-02-02 15:19:21.647828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd342e4bd242b'
down_revision = '3085708c0946'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###