"""auto migration

Revision ID: df1599c83ea3
Revises: 6eb91657c9fc
Create Date: 2025-02-02 10:51:50.938113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1599c83ea3'
down_revision = '6eb91657c9fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###