"""auto migration

Revision ID: fc852df9b6b0
Revises: 39c5b6ed8db9
Create Date: 2025-02-10 18:00:24.088552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc852df9b6b0'
down_revision = '39c5b6ed8db9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###