"""auto migration

Revision ID: fdb30af36a7f
Revises: 338b4ada8a9f
Create Date: 2025-02-14 19:45:41.893658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb30af36a7f'
down_revision = '338b4ada8a9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###